apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-flask-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-flask-website
  template:
    metadata:
      labels:
        app: dummy-flask-website
    spec:
      containers:
      - name: dummy-flask-website
        image: jambalong/dummy-flask-website:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20

